name: sponsor

on:
  pull_request:
    branches:
      - main

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm sponsor
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: Kythuen

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update sponsors.svg [ci skip]'
          add: 'sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
